### ISSUE TITLE
[Map] When entering the Map Antura should be always looking towards the next pin/PS

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#510]
![image](https://user-images.githubusercontent.com/17926293/32415831-55958602-c240-11e7-8898-7d33ccae01b7.png)

**Comment by CatmanIta** [comment]
Fixed in [5580c68]

**Comment by CatmanIta** [comment]
Fixed in [816bc5c]

**Comment by FrancyCavallari** [comment]
I suspect that this fix created a side effect: when you are moving backward, Antura walks to the previous PS and, once reached, it immediately turn 180 degrees to look forward. The same 180 degrees turn happens when Antura passes over a Pin while moving backwards more then one PS.
Antura should not turn once reached a previous PS... he should simply look in the same direction he was moving. The fix was required only when ENTERING the map, in order to initialize Antura sighting correctly.

Example:
![image](https://user-images.githubusercontent.com/17926293/32687974-1251e67e-c6c8-11e7-9ce7-0e76f48f3ad4.png)
I click on the previous PS and Antura walk backwards:
![image](https://user-images.githubusercontent.com/17926293/32687977-2aea5f86-c6c8-11e7-868c-41fc251bef09.png)
Once reached the previous PS, Antura turns immediately to look forward.
![image](https://user-images.githubusercontent.com/17926293/32687980-4ff5a7f4-c6c8-11e7-8527-d4973452410a.png)

**Comment by CatmanIta** [comment]
You are right, fixed in  [d013c2f]

There are a few edge cases:
1. If Antura is at the last PS of a given stage, where should he look when we enter the map? I'd say he should look forward as if there was a pin directly in front of the last one. 
2. If we are in the map in a higher stage (let's say 2) and we select the last PS of the previous stage (stage 1), where should Antura look? (see the attached image)

![image](https://user-images.githubusercontent.com/3244662/32942851-8e282fa8-cb8a-11e7-8038-0b6641185f8d.png)
