### ISSUE TITLE
[MainMenu] the selected profile should be in front of the others

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#595]
Now the Rays of the unselected one are on top of the selected avatar.
![image](https://user-images.githubusercontent.com/17926293/34946330-be36d1b8-fa06-11e7-81b0-959507319f9c.png)

**Comment by StefanoCecere** [comment]
i would suggest to NOT have any ray outside of the circle, or to have a "safe rect area" around the circle to correctly display lists.

**Comment by Demigiant** [comment]
Ray outside was a request and it makese sense, to avoid covering the inner colors. Putting selected profile in front of the others is sadly not possible because of a Unity bug (which also prevents correct re-alignment of spaces when a button gets bigger). I'll see to find a solution then, but this might be long.

**Comment by Demigiant** [comment]
Fixed with the less intrusive rays (since orderings things is not feasible without rebuilding the system)
