### ISSUE TITLE
[Sound error] the yeh with shadda and with skoon are pronounced the same

### ISSUE THREAD

**Issue by zixofranic** [vgwb/Antura_arabic#685]

**Comment by FrancyCavallari** [comment]
Since we have no better way to represent the sound of a letter with Shaddah we decided to keep the same sounf than with Sukun... but they cannot appear as correct and wrong answers in a "phoneme" minigame.
ThrowBalls is not a "phoneme" minigame because you are shown the letter to hit... so there's no possible misunderstanding in this case.
