### ISSUE TITLE
[MissingLetter_letterinword] The game accepts a wrong form of the correct letter as a correct answer

### ISSUE THREAD

**Issue by FrancyCavallari** [vgwb/Antura_arabic#690]
The selected answer is not the correct one (not the same form). The game seems to allow any form of the correct letter. I recall we discussed that we allow the wrong answers to be any letter/any form. But correct answer should be strictly correct letter+correct form of it.

![image](https://user-images.githubusercontent.com/17926293/35337364-3f1fc9f4-011b-11e8-8fe0-a95b0e5f1e59.png)

**Comment by CatmanIta** [comment]
The problem is actually with the game.
Note that MissingLetter treats the data without any concern on what it is (i.e. it knows that the correct one is the first passed), so such issues are inside the game itself

I think I may have fixed the issue, as I found this: 
var parts = ArabicAlphabetHelper.FindLetter(AppManager.I.DB, word.Data, letter.Data, **false**);

And changed it to consider forms too:           
var parts = ArabicAlphabetHelper.FindLetter(AppManager.I.DB, word.Data, letter.Data, **true**);

I think it should be enough, but @davidebarbieri may confirm.

**Comment by CatmanIta** [comment]
Note that the problem was found because the word has two "noon"!
