### ISSUE TITLE
[Baloons] Confusion in when the player loses

### ISSUE THREAD

**Issue by zixofranic** [vgwb/Antura_arabic#708]

**Comment by FrancyCavallari** [comment]
If I remember well, Balloons is not the only game in which there is both a limited number of rounds and a time limit. It is definitely confusing and we should keep only one of the 2: if we have a limited number of rounds then we should get rid of the timer... otherwise we have "infinite" number of rounds within the time limit.
We should double check all games.

**Comment by FrancyCavallari** [comment]
NOTE. in Balloons the Time-Limit is for each round!

**Comment by CatmanIta** [comment]
Timer hidden between rounds in [5a58039]
